
namespace moa {
    export enum CustomPhotonEvents {
        UserMessage = 0,
        UserStartGame = 1,
        EventRequestGameStates = 2,
        EventLoadSceneItemFromServer = 3,
        TakeSeat = 4,
        StartChoosingRole = 5,
        ChooseRole = 6,
        StartGame = 7,
        FirstOneNr = 8,
        nextNr = 9,
        twogameend = 10,
        threegameend = 11,
        tongzhi = 12,
        baowutongzhi = 13,
        toupiaoui = 14,
        piaoshu = 15,
        piaoshu2 = 16,
        piaoshu3 = 17,
        toupiaoend = 18,
        toupiaoend2 = 19,
        toupiaoend3 = 20,
        starttwo = 21,
        startgametongbu = 22,
        onelcftongbu = 23,
        // oneybrtongbu = 24,
        onezgqtongbu = 25,
        twolcftongbu = 26,
        twoybrtongbu = 27,
        twozgqtongbu = 28,
        threelcftongbu = 29,
        threeybrtongbu = 30,
        threezgqtongbu = 31,
        lunci = 32,
        touren = 33,
        tourenjieguo = 34,
        starttoupiao = 35,
        UpdateCurrentTurn = 36,
        UpdateCurrentActor = 37,
        DestroyRoom = 38,
        userinfo = 39,
        OpenGroupChat = 40,
    }
}